name: BiSF
channels:
  - defaults
dependencies:
  - python=3.9.23
  - pip=25.2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - naked==0.1.32
      - networkx==3.2.1
      - numpy==2.0.2
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pycryptodome==3.23.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - shellescape==3.8.1
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - zipp==3.23.0
